# Generated by Django 4.0.3 on 2024-03-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenurl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(default='Registered', max_length=100, null=True),
        ),
    ]
