# Generated by Django 4.0.3 on 2024-03-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenurl', '0002_alter_package_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='history',
            field=models.JSONField(default=list, null=True),
        ),
    ]
